# Generated by Django 3.1.3 on 2020-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('timestamp', models.TextField(blank=True, db_column='Timestamp', null=True)),
                ('email_address', models.TextField(blank=True, db_column='Email Address', null=True)),
                ('nama_kompetisi', models.TextField(blank=True, db_column='Nama Kompetisi', null=True)),
                ('nim', models.FloatField(blank=True, db_column='NIM', null=True)),
                ('nama', models.TextField(blank=True, db_column='Nama', null=True)),
                ('no_hp', models.FloatField(blank=True, db_column='No. HP', null=True)),
                ('lookup', models.TextField(blank=True, db_column='LOOKUP', null=True)),
                ('prestasi', models.TextField(blank=True, db_column='Prestasi', null=True)),
                ('keterangan', models.TextField(blank=True, db_column='Keterangan', null=True)),
                ('evidence_foto_sertifikat_surat_undangan_surat_tugas_field', models.TextField(blank=True, db_column='Evidence (Foto, Sertifikat, Surat Undangan/Surat Tugas)', null=True)),
                ('evaluasi', models.TextField(blank=True, db_column='Evaluasi', null=True)),
                ('updated_by', models.TextField(blank=True, db_column='Updated By', null=True)),
                ('status_follow_up', models.TextField(blank=True, db_column='Status Follow Up', null=True)),
                ('ukm', models.TextField(blank=True, db_column='UKM', null=True)),
                ('bidang_ukm', models.TextField(blank=True, db_column='Bidang UKM', null=True)),
                ('bidang_prestasi', models.TextField(blank=True, db_column='Bidang Prestasi', null=True)),
                ('tahun', models.FloatField(blank=True, db_column='Tahun', null=True)),
                ('triwulan', models.TextField(blank=True, db_column='Triwulan', null=True)),
                ('tw', models.TextField(blank=True, db_column='TW', null=True)),
                ('tahun_akademik', models.TextField(blank=True, db_column='Tahun Akademik', null=True)),
                ('nim_nama', models.TextField(blank=True, db_column='NIM & Nama', null=True)),
                ('fakultas', models.TextField(blank=True, db_column='Fakultas', null=True)),
                ('program_studi', models.TextField(blank=True, db_column='Program Studi', null=True)),
                ('angkatan', models.FloatField(blank=True, db_column='Angkatan', null=True)),
                ('short_fakultas', models.TextField(blank=True, db_column='Short Fakultas', null=True)),
                ('tingkat', models.TextField(blank=True, db_column='Tingkat', null=True)),
                ('kategori_peserta', models.TextField(blank=True, db_column='Kategori Peserta', null=True)),
                ('jumlah_pt', models.FloatField(blank=True, db_column='Jumlah PT', null=True)),
                ('kategori_jumlah_pt', models.TextField(blank=True, db_column='Kategori Jumlah PT', null=True)),
                ('juara', models.TextField(blank=True, db_column='Juara', null=True)),
                ('penyelenggara', models.TextField(blank=True, db_column='Penyelenggara', null=True)),
                ('tanggal_pelaksanaan', models.TextField(blank=True, db_column='Tanggal Pelaksanaan', null=True)),
                ('kategori_juara', models.TextField(blank=True, db_column='Kategori Juara', null=True)),
                ('sudah_menerima_beasiswa', models.FloatField(blank=True, db_column='Sudah Menerima Beasiswa', null=True)),
                ('proper_name', models.TextField(blank=True, db_column='Proper Name', null=True)),
                ('evidence_sudah_lengkap', models.TextField(blank=True, db_column='Evidence Sudah Lengkap', null=True)),
                ('evidence_belum_lengkap', models.TextField(blank=True, db_column='Evidence Belum Lengkap', null=True)),
                ('data_tidak_sesuai', models.TextField(blank=True, db_column='Data Tidak Sesuai', null=True)),
                ('penerima_beasiswa_2019', models.FloatField(blank=True, db_column='Penerima Beasiswa 2019', null=True)),
                ('url_penyelenggara', models.TextField(blank=True, db_column='URL Penyelenggara', null=True)),
                ('skor', models.FloatField(blank=True, db_column='Skor', null=True)),
                ('format_nama_file', models.TextField(blank=True, db_column='Format Nama File', null=True)),
            ],
            options={
                'db_table': 'prestasi',
                'managed': False,
            },
        ),
    ]
